### PR TITLE
lazy firebase initialization

### LINKED ISSUE #8: lazy firebase initialization
This is improvement proposal.

https://github.com/reef-technologies/django-firebase-auth/blob/master/django_firebase_auth/views.py#LL30C5-L30C19

If firebase were to be lazily initialized, then credentials file wouldn't be required until really needed.
This is important as it would simplify for example: django `manage.py collectstatic` in Dockerfile - to which one should not COPY credentials during build - instead mount them afterward to the container.

### PR DESCRIPTION
**Pull request by mjurbanski-reef**
fixes #8

### CODE REVIEW

**Comment by agoncharov-reef** [comment]
So what's the difference? I don't get it. Did you want to delay initialization? Why?

**Comment by mjurbanski-reef** [comment]
@agoncharov-reef  part of motiviation has been described in #8, but here is the exact usecase:

The firebase requires VALID private key to be passed during initialization. Before this change the initialization happend on module import. This means that when you called `manage.py collectstatic` in your Dockerfile you also needed to put some credentials.json in that docker build as well. Putting the production credentials is a no-no in Docker image, and coming up with fake ones is just big pain and pointless exercise IMO.

Probably should have given that description in PR upfront :)

**Comment by agoncharov-reef** [comment]
But it would not initialize in case `SERVICE_ACCOUNT_FILE` is empty, which I believe is indeed empty during collectstatic?

**Comment by mjurbanski-reef** [comment]
That depends on project configuration. If you are using ENV to configure it, and have default value there, then it would (try to) initialize.

the change proposed in PR is directly in line with django recommendations:
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#use-of-django-conf-settings
> Modules should not in general use settings stored in django.conf.settings at the top level (i.e. evaluated when the module is imported).

Maybe I'm not seeing something - is there a reason no to introduce this change?

**Comment by agoncharov-reef** [comment]
It is forbidden to have default value in settings, it should be in an env file :P If you see defaults in settings then it's legacy code.
https://github.com/reef-technologies/handbook#74-restricted-patterns--forbidden-technologies

But django docs reference is a valid point, i didn't know about the restriction. Now it makes sense.

**Comment by agoncharov-reef** [comment]
Now that i think about it, is there a better place to initialize firebase? Doing it in user verification sounds weird. Maybe inside AppConfig.ready() is a better place?

**Review by agoncharov-reef — APPROVED** [review]

**Pull request merged**
